README.md

Fixes `pub_link` in README
Resolves the issue seen on `main` for broken pub_link
/domain @Betterment/alchemist-maintainers 
/no-platform

fix(readme): Update README.md to fix pub link

---

pubspec.yaml

Bump version, fix dependency resolution
/domain @btrautmann @samandmoore 
/platform @btrautmann @samandmoore

chore: Bump version, remove explicit test version

---

.github/workflows/main.yaml
README.md
codecov.yml

Moves to codecov instead of lcov action. Should fix [this issue](https://github.com/Betterment/alchemist/runs/5497674241?check_suite_focus=true)

ci: use codecov instead of lcov reporter

---

.github/CODEOWNERS

chore: add brandon, marcos, and joanna to codeowners

---

README.md

chore: remove duplicate vgv logos

---

lib/alchemist.dart
lib/src/utilities.dart
test/helpers/fake_test_asset_bundle.dart

feat: export test asset bundle

---

CHANGELOG.md
pubspec.yaml

chore: v0.3.1

---

lib/src/interactions.dart
test/src/interactions_test.dart

Small POC for a new scroll interaction using `tester.fling`.

feat: add scroll interaction

---

example/example.md

Updating example code which is not using current alchemist version.
- [ x] 📝 Documentation

chore: Update example to use builder

---

README.md

Thanks for creating this package! After reading through the README, when I click on the repo link at the bottom of the page, I realized that the links were incorrect. This PR updates the repo links.

chore: Fix repo links in README

---

.github/semantic.yml
.github/workflows/main.yaml
.github/workflows/semantic-pull-request.yaml

ci: use semantic-pull-request github action over semantic-pull-requests app

---

CHANGELOG.md
pubspec.yaml

chore: v0.3.3

---

analysis_options.yaml
lib/src/alchemist_config.dart
lib/src/golden_test_group.dart
lib/src/golden_test_scenario.dart
pubspec.yaml
test/smoke_tests/composited_transform_smoke_test.dart
test/smoke_tests/timer_button_smoke_test.dart
test/src/blocked_text_canvas_adapter_test.dart

Upgrades `package:alchemist` to `package:very_good_analysis` 3.0.0.

chore: upgrade to very_good_analysis 3.0.0

---

lib/src/alchemist_config.dart
lib/src/golden_test_adapter.dart
lib/src/golden_test_group.dart
lib/src/golden_test_scenario.dart
lib/src/golden_test_scenario_constraints.dart
pubspec.yaml
test/smoke_tests/composited_transform_smoke_test.dart
test/smoke_tests/timer_button_smoke_test.dart

Downgraded the minimum dart version from 2.17.0 to 2.16.2.

chore: downgrade min sdk to 2.16.2

---

CHANGELOG.md
pubspec.yaml

chore: v0.4.1

---

lib/src/golden_test_runner.dart

fix: properly clear window size overrides after test run

---

CHANGELOG.md
pubspec.yaml

chore: v0.5.1

---

.github/workflows/main.yaml
CHANGELOG.md

I upgraded to flutter 3.7.0 and bumped the version to a stable minor release.

chore: upgrade to flutter 3.7.0

---

.github/workflows/post_merge.yaml

ci: fix flutter version on post-merge workflow

---

CHANGELOG.md
pubspec.yaml

chore: release prep for 0.6.1

---

.github/workflows/post_merge.yaml
CHANGELOG.md
pubspec.yaml

chore: v0.7.0

---

RECOMMENDED_SETUP_GUIDE.md

docs: fix a small typo under RECOMMENDED_SETUP_GUIDE.md

---

CHANGELOG.md
pubspec.yaml

chore: prep 0.8.0 release

---

CHANGELOG.md
pubspec.yaml

chore: prep 0.9.0 release

---

.github/CODEOWNERS
CHANGELOG.md
pubspec.yaml

chore: prep 0.10.0 release

---

CHANGELOG.md
pubspec.yaml

chore: prep 0.12.0
